### ISSUE TITLE
run error

### ISSUE THREAD

**Issue by mana-ai** [giantsol/todo-app#82]
```
Running "flutter pub get" in Blue-Diary...                          0.7s

Launching lib/main.dart on iPhone Xʀ in debug mode...

Compiler message:
lib/presentation/settings/SettingsBloc.dart:9:8: Error: Error when reading 'lib/Secrets.dart': No such file or
directory
import 'package:todo_app/Secrets.dart';
       ^
lib/presentation/settings/SettingsBloc.dart:129:44: Error: The getter 'SENDGRID_AUTHORIZATION' isn't defined for the
class 'SettingsBloc'.
 - 'SettingsBloc' is from 'package:todo_app/presentation/settings/SettingsBloc.dart'
 ('lib/presentation/settings/SettingsBloc.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named
'SENDGRID_AUTHORIZATION'.
          HttpHeaders.authorizationHeader: SENDGRID_AUTHORIZATION,
                                           ^^^^^^^^^^^^^^^^^^^^^^
Exception: Errors during snapshot creation: null
#0      KernelSnapshot.build (package:flutter_tools/src/build_system/targets/dart.dart:230:7)
<asynchronous suspension>
#1      _BuildInstance._invokeInternal (package:flutter_tools/src/build_system/build_system.dart:526:25)
<asynchronous suspension>
#2      _BuildInstance.invokeTarget.<anonymous closure>
(package:flutter_tools/src/build_system/build_system.dart:481:35)
#3      new Future.sync (dart:async/future.dart:222:31)
#4      AsyncMemoizer.runOnce (package:async/src/async_memoizer.dart:43:45)
#5      _BuildInstance.invokeTarget (package:flutter_tools/src/build_system/build_system.dart:481:21)
<asynchronous suspension>
<asynchronous suspension>
#6      BuildSystem.build (package:flutter_tools/src/build_system/build_system.dart:419:36)
#7      _AsyncAwaitCompleter.start (dart:async-patch/async_patch.dart:43:6)
#8      BuildSystem.build (package:flutter_tools/src/build_system/build_system.dart:400:28)
#9      buildWithAssemble (package:flutter_tools/src/bundle.dart:125:48)
#10     _AsyncAwaitCompleter.start (dart:async-patch/async_patch.dart:43:6)
#11     buildWithAssemble (package:flutter_tools/src/bundle.dart:99:31)
#12     BundleBuilder.build (package:flutter_tools/src/bundle.dart:75:11)
#13     _AsyncAwaitCompleter.start (dart:async-patch/async_patch.dart:43:6)
#14     BundleBuilder.build (package:flutter_tools/src/bundle.dart:52:21)
#15     IOSSimulator._sideloadUpdatedAssetsForInstalledApplicationBundle
(package:flutter_tools/src/ios/simulators.dart:453:28)
#16     IOSSimulator._setupUpdatedApplicationBundle (package:flutter_tools/src/ios/simulators.dart:420:11)
#17     _AsyncAwaitCompleter.start (dart:async-patch/async_patch.dart:43:6)
#18     IOSSimulator._setupUpdatedApplicationBundle (package:flutter_tools/src/ios/simulators.dart:419:46)
#19     IOSSimulator.startApp (package:flutter_tools/src/ios/simulators.dart:352:15)
#20     _AsyncAwaitCompleter.start (dart:async-patch/async_patch.dart:43:6)
#21     IOSSimulator.startApp (package:flutter_tools/src/ios/simulators.dart:339:32)
#22     FlutterDevice.runHot (package:flutter_tools/src/resident_runner.dart:393:54)
#23     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:71:64)
#24     _rootRunUnary (dart:async/zone.dart:1132:38)
#25     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#26     _FutureListener.handleValue (dart:async/future_impl.dart:137:18)
#27     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:678:45)
#28     Future._propagateToListeners (dart:async/future_impl.dart:707:32)
#29     Future._completeWithValue (dart:async/future_impl.dart:522:5)
#30     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:30:15)
#31     _completeOnAsyncReturn (d
```

**Comment by giantsol** [comment]
Hi!
Yes, you would get a build error first because that `SENDGRID_AUTHORIZATION` variable is not pushed to github (that's my own secret key).
So simple solution is to remove `import 'package:todo_app/Secrets.dart';` line and change `HttpHeaders.authorizationHeader: SENDGRID_AUTHORIZATION,` to `HttpHeaders.authorizationHeader: '',` and it should build fine :)

I've written about this issue [here](https://github.com/giantsol/Blue-Diary#usage) also!

**Comment by giantsol** [comment]
Closing this issue.
Reopen it if you still have the issue.
Thanks :)
